apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway  # Esta etiqueta debe coincidir con la del pod de `api-gateway`
  ports:
    - protocol: TCP
      port: 80            # Puerto de exposición para acceder externamente
      targetPort: 8080    # Puerto en el que `api-gateway` está escuchando internamente
