ARG BASE_ID

FROM builder:${BASE_ID}
ARG REVISION
ARG SONAR_MAVEN_GOAL
ARG SONAR_HOST_URL
ARG SONAR_AUTH_TOKEN
ARG MVN_EXTRA_ARGS=""
RUN mvn --batch-mode ${SONAR_MAVEN_GOAL} -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=$SONAR_AUTH_TOKEN -Drevision=${REVISION} ${MVN_EXTRA_ARGS}
