spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    discovery:
      enable: true

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
