apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: config-server
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: customers-service
          image: ross1832/spring-petclinic-customers-service:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888/
            - name: SPRING_PROFILES_ACTIVE
              value: docker,mysql
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: petclinic
          ports:
            - containerPort: 8081
