apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ross1832/spring-petclinic-api-gateway:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888/
          ports:
            - containerPort: 8080
