apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: springcommunity/spring-petclinic-api-gateway
          imagePullPolicy: IfNotPresent
          name: api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
