apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-server
  name: config-server
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - image: springcommunity/spring-petclinic-config-server
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - -I
                - http://config-server:8888
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          name: config-server
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
