apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ghcr.io/ross1832/spring-petclinic-cloud-config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
