apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30088

