apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 38081
      targetPort: 8081
