apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: config-server
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: config-server
          image: ross1832/spring-petclinic-config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
      containers:
        - name: discovery-server
          image: ross1832/spring-petclinic-discovery-server:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888/
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          ports:
            - containerPort: 8761
