apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: petclinic-dev
spec:
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: ${DOCKER_USERNAME}/spring-petclinic-discovery-server:${IMAGE_TAG}
        ports:
        - containerPort: 8761
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: petclinic-dev
spec:
  selector:
    app: discovery-server
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30761
  type: NodePort