---
# discovery-server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: petclinic-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: springcommunity/spring-petclinic-discovery-server:latest
        ports:
        - containerPort: 8761
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# discovery-server-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: petclinic-dev
spec:
  selector:
    app: discovery-server
  ports:
  - port: 8761
    targetPort: 8761
  type: ClusterIP
---