apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: ross1832/spring-petclinic-discovery-server:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888/
          ports:
            - containerPort: 8761
