apiVersion: v1
kind: Service
metadata:
  labels:
    app: genai-service
  name: genai-service
  namespace: petclinic
spec:
  type: NodePort
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    app: genai-service
