apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-server
  name: grafana-server
  namespace: petclinic
spec:
  type: NodePort
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3000
  selector:
    app: grafana-server
