apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-server
  name: grafana-server
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
        - image: grafana-server
          name: grafana-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
