apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tracing-server
  name: tracing-server
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
        - image: openzipkin/zipkin
          name: tracing-server
          ports:
            - containerPort: 9411
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
