apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: petclinic-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - name: vets-service
        image: ${DOCKER_USERNAME}/spring-petclinic-vets-service:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: petclinic-dev
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8080
      nodePort: 30082
  selector:
    app: vets-service