apiVersion: v1
kind: Service
metadata:
  labels:
    app: visits-service
  name: visits-service
  namespace: petclinic
spec:
  type: NodePort
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    app: visits-service
