apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: ross1832/spring-petclinic-visits-service:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888/
            - name: SPRING_PROFILES_ACTIVE
              value: docker,mysql
            - name: MYSQL_URL
              value: jdbc:mysql://mysql:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              value: petclinic
          ports:
            - containerPort: 8082
