// src/test/java/org/springframework/samples/petclinic/vets/model/SpecialtyTest.java
package org.springframework.samples.petclinic.vets.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class SpecialtyTest {

    private Specialty specialty;

    @BeforeEach
    void setUp() {
        specialty = new Specialty();
    }

    @Test
    void testGetId_NotSet() {
        // ID is generated by persistence, cannot be set directly.
        // Test that it's null initially.
        assertNull(specialty.getId(), "ID should be null initially as it's generated by persistence");
    }

    @Test
    void testSetAndGetName() {
        String testName = "Radiology";
        specialty.setName(testName);
        assertEquals(testName, specialty.getName(), "setName should correctly set the name");
    }

    @Test
    void testGetName_NotSet() {
        assertNull(specialty.getName(), "Name should be null if not set");
    }

    // No equals/hashCode/toString defined, so no tests for those.
}