FROM openjdk:17-alpine

ARG STAGE
ARG SERVICE

WORKDIR /opt/app

COPY ${SERVICE}/target/*.jar /opt/app/app.jar

EXPOSE 8888

ENV SPRING_PROFILES_ACTIVE=${STAGE}

ENTRYPOINT ["java", "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", "-jar", "/opt/app/app.jar"]
