  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: admin-server
    labels:
      app: admin-server
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: admin-server
    template:
      metadata:
        labels:
          app: admin-server
      spec:
        containers:
          - name: admin-server
            image: petdistriacr.azurecr.io/spring-petclinic-admin-server:latest
            ports:
              - containerPort: 9090
            resources:
              limits:
                memory: "512Mi"
                cpu: "500m"
              requests:
                memory: "256Mi"
                cpu: "250m"
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 30
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 15
              periodSeconds: 5
        imagePullSecrets:
          - name: acr-auth
        restartPolicy: Always
