apiVersion: v1
kind: Service
metadata:
  name: customers-service
  labels:
    app: customers-service
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: customers-service
  type: ClusterIP