apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  ports:
    - name: http
      port: 8761
      targetPort: 8761
  selector:
    app: discovery-server
  type: ClusterIP