pipeline {
    agent any


    stages {
        stage('Checkout Code') {
            steps {
                script {
                    echo "Checking out code from branch: ${env.BRANCH_NAME}"
                    checkout scm
                }
            }
        }

        stage('Setup Environment') {
            steps {
                sh 'sudo dnf install -y java-17-openjdk maven'
                sh 'sudo dnf install maven -y'
            }
        }

        stage('Run Unit Tests') {
            steps {
                script {
                    echo "Running tests for ${params.SERVICE}"
                    sh "./mvnw -pl spring-petclinic-vets-service test"
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                    jacoco execPattern: '**/target/jacoco.exec'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "./mvnw clean install -pl spring-petclinic-vets-service"
            }
        }
    }

    post {
        success { echo "Pipeline completed successfully!" }
        failure { echo "Pipeline failed!" }
    }
}
